Setup code for chsh inequality
ubsuny/CP1-24-HW1 pull request #31
Opened 2024-09-20 20:22 UTC by jkblc

Setup code and start of backend connection. Should be compatible with previous pull request #29

2024-09-21 00:15 UTC, laserlab requested changes
Could you comment a little more what each line does using inline comments?

2024-09-21 00:15 UTC, laserlab commented on chsh_inequality.py
> +backend = service.least_busy(operational=True, simulator=False, min_num_qubits=127)
Could you set the minimum number of qubits to a more useful value for the Bell’s inequality problem?

2024-09-21 15:55 UTC, laserlab commented
Check PR #29 . you can add the setup code in a new file and then later the code will be put together in a new file.

2024-09-23 18:01 UTC, jkblc commented
Yes, I'll pull the updated repository and add the setup code to quantumcode.py
I'll set the minimum qubits to 2 for now

2024-09-23 18:01 UTC, closed without merging