Added Documentation for IBM Quantum API
ubsuny/CP1-24-HW1 pull request #48
Opened 2024-09-22 14:54 UTC by iglesias-cardinale

I added an actual markdown file for what I put in issue #26. This should be useful for anyone who is having trouble connecting their code to the IBM Quantum Computer.

2024-09-22 20:59 UTC, laserlab requested changes
- remove devcontainer.json
 - better markdown code formatting

2024-09-22 20:59 UTC, laserlab commented on IBM Quantum API Information.md
> +"**QiskitRuntimeService.save_account(token="YOUR_API_TOKEN", channel="ibm_quantum")**
Prettier markdown would be to use a code markup such as:
```markdown

> ```python
> QiskitRuntimeService.save_account(token="YOUR_API_TOKEN", channel="ibm_quantum")
> ```

```

2024-09-22 20:59 UTC, laserlab commented on .devcontainer/qiskit/devcontainer.json
Looks like this should not be part of the PR. Please remove

2024-09-22 20:59 UTC, laserlab commented
add label and milestone to PR

2024-09-23 20:59 UTC, laserlab approved these changes
looks good now

2024-09-23 20:59 UTC, merged

2024-09-24 15:25 UTC, iglesias-cardinale commented
I'm glad this worked out. I basically made an entirely new branch in my forked repository and then tried to merge which I think was unnecessary.